title: Niklas Jordan
email: hello@niklasjordan.com
description: Full-time technology advocate – part-time Earth science student. I am passionate about natural hazards, Earth observation, climate, data science, open data, low-cost technology, human rights & tech ethics.
baseurl: ""
url: "https://www.niklasjordan.com"

# Build settings
# theme: no-style-please
# remote_theme: no-style-please
plugins:
  - jekyll-feed

collections:
  links:
    output: true
  speaking:
    output: false

feed:
  collections:
    links:
      path: "/links.xml"

navigation:
  - text: Start here
    url: /
  - text: About me
    url: /about.html
  - text: Publications & Talks
    url: /speaking.html
  - text: Blog
    url: /blog.html
